# -*- coding: utf-8 -*-
"""example_base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pzw1edoq5OttZcCM7US6ywvsOf40JD3b
"""

!git clone https://github.com/jsaj/Multi_DES.git

!pip install deslib

from Multi_DES.multides import MULTIDES

import pandas as pd
from glob import glob

import warnings
warnings.filterwarnings("ignore")

# path of datasets to predict
path = '/content/Multi_DES/benchmark-execution/benchmarks/datasets/RELINK/*'

# read and create dataframe (dataset) with all projects for predict
dataset = []
for project_url in glob(path):
  productName = project_url.split('/')[len(project_url.split('/'))-1].split('.csv')[0]
  df = pd.read_csv(project_url)
  df.insert(0, 'productName', productName)
  dataset.append(df)
dataset = pd.concat(dataset).reset_index(drop=True)

dataset.head()

#create Multi-DES object to predict dataset
obj = MULTIDES(dataset)

#get Multi-DE performance after predict the dataset. Return a pandas dataframe
obj.performances